# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_wordseg', [dirname(__file__)])
        except ImportError:
            import _wordseg
            return _wordseg
        if fp is not None:
            try:
                _mod = imp.load_module('_wordseg', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _wordseg = swig_import_helper()
    del swig_import_helper
else:
    import _wordseg
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class SwigPyIterator:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wordseg.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _wordseg.SwigPyIterator_value(self)
    def incr(self, n = 1): return _wordseg.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _wordseg.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _wordseg.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _wordseg.SwigPyIterator_equal(self, *args)
    def copy(self): return _wordseg.SwigPyIterator_copy(self)
    def next(self): return _wordseg.SwigPyIterator_next(self)
    def __next__(self): return _wordseg.SwigPyIterator___next__(self)
    def previous(self): return _wordseg.SwigPyIterator_previous(self)
    def advance(self, *args): return _wordseg.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _wordseg.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _wordseg.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _wordseg.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _wordseg.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _wordseg.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _wordseg.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _wordseg.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectorstr:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorstr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorstr, name)
    __repr__ = _swig_repr
    def iterator(self): return _wordseg.vectorstr_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _wordseg.vectorstr___nonzero__(self)
    def __bool__(self): return _wordseg.vectorstr___bool__(self)
    def __len__(self): return _wordseg.vectorstr___len__(self)
    def pop(self): return _wordseg.vectorstr_pop(self)
    def __getslice__(self, *args): return _wordseg.vectorstr___getslice__(self, *args)
    def __setslice__(self, *args): return _wordseg.vectorstr___setslice__(self, *args)
    def __delslice__(self, *args): return _wordseg.vectorstr___delslice__(self, *args)
    def __delitem__(self, *args): return _wordseg.vectorstr___delitem__(self, *args)
    def __getitem__(self, *args): return _wordseg.vectorstr___getitem__(self, *args)
    def __setitem__(self, *args): return _wordseg.vectorstr___setitem__(self, *args)
    def append(self, *args): return _wordseg.vectorstr_append(self, *args)
    def empty(self): return _wordseg.vectorstr_empty(self)
    def size(self): return _wordseg.vectorstr_size(self)
    def clear(self): return _wordseg.vectorstr_clear(self)
    def swap(self, *args): return _wordseg.vectorstr_swap(self, *args)
    def get_allocator(self): return _wordseg.vectorstr_get_allocator(self)
    def begin(self): return _wordseg.vectorstr_begin(self)
    def end(self): return _wordseg.vectorstr_end(self)
    def rbegin(self): return _wordseg.vectorstr_rbegin(self)
    def rend(self): return _wordseg.vectorstr_rend(self)
    def pop_back(self): return _wordseg.vectorstr_pop_back(self)
    def erase(self, *args): return _wordseg.vectorstr_erase(self, *args)
    def __init__(self, *args): 
        this = _wordseg.new_vectorstr(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _wordseg.vectorstr_push_back(self, *args)
    def front(self): return _wordseg.vectorstr_front(self)
    def back(self): return _wordseg.vectorstr_back(self)
    def assign(self, *args): return _wordseg.vectorstr_assign(self, *args)
    def resize(self, *args): return _wordseg.vectorstr_resize(self, *args)
    def insert(self, *args): return _wordseg.vectorstr_insert(self, *args)
    def reserve(self, *args): return _wordseg.vectorstr_reserve(self, *args)
    def capacity(self): return _wordseg.vectorstr_capacity(self)
    __swig_destroy__ = _wordseg.delete_vectorstr
    __del__ = lambda self : None;
vectorstr_swigregister = _wordseg.vectorstr_swigregister
vectorstr_swigregister(vectorstr)

class wordseg:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, wordseg, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, wordseg, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _wordseg.new_wordseg()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wordseg.delete_wordseg
    __del__ = lambda self : None;
    def load_dict(self, *args): return _wordseg.wordseg_load_dict(self, *args)
    def segment(self, *args): return _wordseg.wordseg_segment(self, *args)
wordseg_swigregister = _wordseg.wordseg_swigregister
wordseg_swigregister(wordseg)

# This file is compatible with both classic and new-style classes.


